name: npo-proxy
services:
  - name: web
    git:
      repo_clone_url: https://github.com/kaddio/platform.git
      branch: master
    github:
      repo: kaddio/platform
      branch: master
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    source_dir: ./npo-proxy
    envs:
      - key: PORT
        value: "3900"
    http_port: 3900
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /