services:
   - type: web
     name: platform
     env: node
     buildCommand: npm install && npm run build
     startCommand: node build/index.js
     plan: standard
     branch: tailwind
     region: frankfurt
     envVars:
      - key: NODE_VERSION
        value: 16.14