services:
  - type: web
    name: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    branch: master
    rootDir: web
    pullRequestPreviewsEnabled: true
    domains:
      - kaddio.com
    region: frankfurt
    envVars:
      - key: NODE_VERSION
        value: 16.14

  - type: web
    name: changelog
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    #  startCommand: npm run start
    #  plan: free
    branch: master
    rootDir: changelog
    domains:
      - changelog.kaddio.com
    envVars:
      - key: NEXT_PUBLIC_SITE_URL
        value: changelog.kaddio.com

  - type: web
    name: proxy
    env: docker
    plan: free
    branch: master
    rootDir: proxy
    region: frankfurt

  - type: web
    name: jitsi
    env: static
    staticPublishPath: ./
    branch: master
    rootDir: jitsi
