services:
   - type: web
     name: web
     env: node
     buildCommand: npm install && npm run build
     startCommand: node build/index.js
     plan: free
     branch: tailwind
     rootDir: web
     region: frankfurt
     envVars:
      - key: NODE_VERSION
        value: 16.14

   - type: web
     name: changelog
     env: node
     buildCommand: npm install && npm run build
     startCommand: npm run start
     plan: free
     branch: tailwind
     rootDir: changelog
     region: frankfurt
     envVars:
      - key: NODE_VERSION
        value: 16.14

   - type: web
     name: proxy
     env: node
     buildCommand: npm install
     startCommand: node index.js
     plan: free
     branch: tailwind
     rootDir: proxy
     region: frankfurt
     envVars:
      - key: NODE_VERSION
        value: 16.14

   - type: web
     name: jitsi
     env: static
     staticPublishPath: ./
     plan: free
     branch: tailwind
     rootDir: jitsi
