version: '3'
services:
  app:
    build: .
    ports:
      - "3900:3900"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3900
      - TARGET=https://ffde-94-191-137-198.ngrok-free.app
    extra_hosts:
      - "host.docker.internal:host-gateway"