version: '3'
services:
  app:
    build: .
    ports:
      - "3900:3900"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3900
      - TARGET=$TARGET
    extra_hosts:
      - "host.docker.internal:host-gateway"