name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./proxy
        push: true
        tags: kaddio/kaddio:proxy-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to VPS and run update script
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: kaddiotestarnpo.kaddio.com
        username: root
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: sh /var/lib/cloud/scripts/per-boot/update.sh